// Generated by CoffeeScript 1.6.1
/*
 debouncedresize: special jQuery event that happens once after a window resize

 latest version and complete README available on Github:
 https://github.com/louisremi/jquery-smartresize/blob/master/jquery.debouncedresize.js

 Copyright 2011 @louis_remi
 Licensed under the MIT license.
*/

var $event, $special, BLANK, Grid;

$event = $.event;

$special;

resizeTimeout;

$special = $event.special.debouncedresize = {
  setup: function() {
    return $(this).on("resize", $special.handler);
  },
  teardown: function() {
    return $(this).off("resize", $special.handler);
  },
  handler: function(event, execAsap) {
    var args, context, dispatch, resizeTimeout;
    context = this;
    args = arguments;
    dispatch = function() {
      event.type = "debouncedresize";
      return $event.dispatch.apply(context, args);
    };
    if (resizeTimeout) {
      clearTimeout(resizeTimeout);
    }
    if (execAsap) {
      return dispatch();
    } else {
      return resizeTimeout = setTimeout(dispatch, $special.threshold);
    }
  },
  threshold: 250
};

/* 
======================= imagesLoaded Plugin ===============================
https://github.com/desandro/imagesloaded

$('#my-container').imagesLoaded(myFunction)
execute a callback when all images have loaded.
needed because .load() doesn't work on cached images
callback function gets image collection as argument
this is the container

original: MIT license. Paul Irish. 2010.
contributors: Oren Solomianik, David DeSandro, Yiannis Chatzikonstantinou

blank image data-uri bypasses webkit log warning (thx doug jones)
*/


BLANK = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';

$.fn.imagesLoaded = function(callback) {
  var $images, $this, broken, deferred, doneLoading, hasNotify, imgLoaded, loaded, proper;
  $this = this;
  if ($.isFunction($.Deferred)) {
    deferred = $.Deferred();
  } else {
    deferred = 0;
  }
  hasNotify = $.isFunction(deferred.notify);
  $images = $this.find('img').add($this.filter('img'));
  loaded = [];
  proper = [];
  broken = [];
  if ($.isPlainObject(callback)) {
    $.each(callback, function(key, value) {
      if (key === 'callback') {
        return callback = value;
      } else if (deferred) {
        return deferred[key](value);
      }
    });
  }
  doneLoading = function() {
    var $broken, $proper;
    $proper = $(proper);
    $broken = $(broken);
    if (deferred) {
      if (broken.length) {
        deferred.reject($images, $proper, $broken);
      } else {
        deferred.resolve($images);
      }
    }
    if ($.isFunction(callback)) {
      return callback.call($this, $images, $proper, $broken);
    }
  };
  imgLoaded = function(img, isBroken) {
    if (img.src === BLANK || $.inArray(img, loaded) !== -1) {
      return;
    }
    loaded.push(img);
    if (isBroken) {
      broken.push(img);
    } else {
      proper.push(img);
    }
    $.data(img, 'imagesLoaded', {
      isBroken: isBroken,
      src: img.src
    });
    if (hasNotify) {
      deferred.notifyWith($(img), [isBroken, $images, $(proper), $(broken)]);
    }
    if ($images.length === loaded.length) {
      setTimeout(doneLoading);
      return $images.unbind('.imagesLoaded');
    }
  };
  if (!$images.length) {
    doneLoading();
  } else {
    $images.bind('load.imagesLoaded error.imagesLoaded', function(event) {
      return imgLoaded(event.target, event.type === 'error');
    }).each(function(i, el) {
      var cached, src;
      src = el.src;
      cached = $.data(el, 'imagesLoaded');
      if (cached && cached.src === src) {
        imgLoaded(el, cached.isBroken);
        return;
      }
      if (el.complete && el.naturalWidth !== void 0) {
        imgLoaded(el, el.naturalWidth === 0 || el.naturalHeight === 0);
      }
      if (el.readyState || el.complete) {
        el.src = BLANK;
        return el.src = src;
      }
    });
  }
  if (deferred) {
    return deferred.promise($this);
  } else {
    return $this;
  }
};

Grid = (function() {
  var $body, $grid, $items, $window, current, init, marginExpanded, previewPos, saveItemInfo, scrollExtra, settings, support, transEndEventName, transEndEventNames;
  $grid = $('#og-grid');
  $items = $grid.children('li');
  current = -1;
  previewPos = -1;
  scrollExtra = 0;
  marginExpanded = 10;
  $window = $(window);
  winsize;
  $body = $('html, body');
  transEndEventNames = {
    'WebkitTransition': 'webkitTransitionEnd',
    'MozTransition': 'transitionend',
    'OTransition': 'oTransitionEnd',
    'msTransition': 'MSTransitionEnd',
    'transition': 'transitionend'
  };
  transEndEventName = transEndEventNames[Modernizr.prefixed('transition')];
  support = Modernizr.csstransitions;
  settings = {
    minHeight: 500,
    speed: 350,
    easing: 'ease'
  };
  init = function(config) {
    settings = $.extend(true, {}, settings, config);
    return $grid.imagesLoaded(function() {
      saveItemInfo(true);
      getWinSize();
      return initEvents();
    });
  };
  return saveItemInfo = function(saveheight) {
    return $items.each(function() {
      var $item;
      $item = $(this);
      $item.data('offsetTop', $item.offset().top);
      if (saveheight) {
        return $item.data('height', $item.height());
      }
    });
  };
});
